description = "Amazon Managed Buildpacks based on Amazon Linux System"

[[buildpacks]]
  uri = "./python"

[[buildpacks]]
  uri = "./pip3"

[[buildpacks]]
  uri = "./nodejs"

[[order]]
  [[order.group]]
    id = "python-runtime"
    version = "0.0.1"
  [[order.group]]
    id = "python-pip3"
    version = "0.0.1"
    optional = true

[[order]]
  [[order.group]]
    id = "nodejs-runtime"
    version = "0.0.1"


[stack]
  build-image = "aws-buildpack-build:latest"
  id = "aws-23"
  run-image = "aws-buildpack-run:latest"