api = "0.8"

[buildpack]
  homepage = "https://github.com/aws/aws-buildpacks"
  id = "python-runtime"
  version = "0.0.1"
  name = "AWS Managed Buildpack for Python Runtime"
  sbom-formats = ["application/vnd.cyclonedx+json", "application/spdx+json", "application/vnd.syft+json"]

[metadata]
    [metadata.default-versions]
        python = "3.11.*"
    
    [[metadata.dependencies]]
        checksum = "sha256:aaf7e556c9caf62410dade6a4a6392d2df42ddf4138e9f52032cd2d09ab730e5"
        cpe = "cpe:2.3:a:a:python:py:3.11.2:*:*:*:*:*:*:*"
        licenses = ["BSD-3-Clause"]
        name = "python"
        id = "python"
        uri = "https://github.com/dreamyang-liu/Buildpack/releases/download/Dependency/python3.11.2.tar.gz"
        version = "3.11.2"
        strip-components = 0
        stacks = ["*"]

[[stacks]]
 id = "*"